server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: payment
          uri: http://localhost:8032
          predicates:
            - Path=/payments/**,
        # - id: review
        #   uri: http://localhost:8052
        #   predicates:
        #     - Path=/reviews/**
        - id: reservation
          uri: http://localhost:8072
          predicates:
            - Path=/reservations/**, 
        - id: notification
          uri: http://localhost:8073
          predicates:
            - Path=/notifications/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST
        - id: orderapp
          uri: http://localhost:8082
          predicates:
            - Path=/orders/**, /orderPages/**
        - id: user
          uri: http://localhost:8083
          predicates:
            - Path=/users/**, 
        - id: marketing
          uri: http://localhost:8084
          predicates:
            - Path=/promotions/**, /coupons/**, 
        - id: store
          uri: http://localhost:8085
          predicates:
            - Path=/menus/**, /stores/**, /getMenus/**
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            exposedHeaders:
              - "X-Total-Count"
              - "Link"
              - "Access-Control-Allow-Origin"
              - "Access-Control-Allow-Credentials"
            allowCredentials: true
            maxAge: 3600

---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: orderapp
          uri: http://orderapp:8080
          predicates:
            - Path=/orders/**, 
        - id: user
          uri: http://user:8080
          predicates:
            - Path=/users/**, 
        - id: marketing
          uri: http://marketing:8080
          predicates:
            - Path=/promotions/**, /coupons/**, 
        - id: store
          uri: http://store:8080
          predicates:
            - Path=/menus/**, /stores/**, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
